### ISSUE TITLE
Not working in 4.1.0

### ISSUE THREAD

**Issue by adrianobr** [ncoders/redmine_local_avatars#24]
NameError: undefined method `avatar' for module `ApplicationHelper'
/usr/src/redmine/plugins/redmine_local_avatars/lib/application_helper_avatar_patch.rb:25:in `alias_method'
/usr/src/redmine/plugins/redmine_local_avatars/lib/application_helper_avatar_patch.rb:25:in `block in included'
/usr/src/redmine/plugins/redmine_local_avatars/lib/application_helper_avatar_patch.rb:24:in `class_eval'
/usr/src/redmine/plugins/redmine_local_avatars/lib/application_helper_avatar_patch.rb:24:in `included'
/usr/src/redmine/plugins/redmine_local_avatars/init.rb:35:in `include'
/usr/src/redmine/plugins/redmine_local_avatars/init.rb:35:in `block in <top (required)>'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:426:in `instance_exec'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `catch'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `each'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `invoke_before'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/bundle/gems/activesupport-5.2.4.1/lib/active_support/reloader.rb:89:in `prepare!'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
/usr/src/redmine/config/environment.rb:16:in `<top (required)>'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
/usr/local/bundle/gems/railties-5.2.4.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/bundle/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

**Comment by tiurlumbangaol** [comment]
hi, maybe you could fork from : https://github.com/taqueci/redmine_local_avatars

**Comment by Jamalc0m** [comment]
Same here

root@redmine .../www/redmine# rake redmine:plugins:migrate RAILS_ENV=production --trace
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: undefined method `avatar' for module `ApplicationHelper'
/var/www/redmine/plugins/redmine_local_avatars/lib/application_helper_avatar_patch.rb:25:in `alias_method'
/var/www/redmine/plugins/redmine_local_avatars/lib/application_helper_avatar_patch.rb:25:in `block in included'
/var/www/redmine/plugins/redmine_local_avatars/lib/application_helper_avatar_patch.rb:24:in `class_eval'
/var/www/redmine/plugins/redmine_local_avatars/lib/application_helper_avatar_patch.rb:24:in `included'
/var/www/redmine/plugins/redmine_local_avatars/init.rb:35:in `include'
/var/www/redmine/plugins/redmine_local_avatars/init.rb:35:in `block in <top (required)>'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:426:in `instance_exec'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:606:in `block (2 levels) in default_terminator'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `catch'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:605:in `block in default_terminator'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `each'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:513:in `invoke_before'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/reloader.rb:89:in `prepare!'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.2.4.1/lib/rails/application/finisher.rb:63:in `block in <module:Finisher>'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
/var/www/redmine/config/environment.rb:16:in `<top (required)>'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/railties-5.2.4.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/local/rbenv/versions/2.3.5/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/usr/local/rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/rbenv/versions/2.3.5/bin/rake:23:in `load'
/usr/local/rbenv/versions/2.3.5/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

**Comment by Jamalc0m** [comment]
@tiurlumbangaol you may have a look into this:

https://github.com/ncoders/redmine_local_avatars/issues/26

**Comment by dup2** [comment]
Fixed with 1.0.6
